# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Wan-Ting
tagline:          '工程師筆記'
description:      'Sharing Software, UK information and mood in English or Chinese ;)'
url:              https://wanting82.github.io
#baseurl:

author:
  name:           'Wan-Ting Chen'
  url:            https://twitter.com/WantingChen6

paginate:         5

# Social media links in footer
instagram: "w.t_schen"
email: "silviachen.825@gmail.com"
linkedin: "silviachen825"
github: "wanting82"


# Custom vars
version:          1.0.0

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
